<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Result;

class ResultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Result::create( [
            'id'=>1,
            'fixture_id'=>1,
            'matchday'=>1,
            'home_team'=>6,
            'away_team'=>13,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>3,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>0.33,
            'away_xG'=>2.08,
            'home_ballPossession'=>34,
            'away_ballPossession'=>66,
            'home_shots'=>6,
            'away_shots'=>17,
            'home_shotsOnTarget'=>1,
            'away_shotsOnTarget'=>8,
            'home_corners'=>0,
            'away_corners'=>1,
            'home_offsides'=>0,
            'away_offsides'=>1,
            'home_fouls'=>11,
            'away_fouls'=>8,
            'home_yellow'=>0,
            'away_yellow'=>0,
            'home_red'=>1,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:22:00',
            'updated_at'=>'2024-01-24 17:22:00'
            ] );
                        
            Result::create( [
            'id'=>2,
            'fixture_id'=>2,
            'matchday'=>1,
            'home_team'=>1,
            'away_team'=>16,
            'homeTeam_goal'=>2,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>0.83,
            'away_xG'=>1.18,
            'home_ballPossession'=>78,
            'away_ballPossession'=>22,
            'home_shots'=>15,
            'away_shots'=>6,
            'home_shotsOnTarget'=>7,
            'away_shotsOnTarget'=>2,
            'home_corners'=>8,
            'away_corners'=>3,
            'home_offsides'=>2,
            'away_offsides'=>1,
            'home_fouls'=>12,
            'away_fouls'=>12,
            'home_yellow'=>2,
            'away_yellow'=>2,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:23:01',
            'updated_at'=>'2024-01-24 17:23:01'
            ] );
                        
            Result::create( [
            'id'=>3,
            'fixture_id'=>3,
            'matchday'=>1,
            'home_team'=>3,
            'away_team'=>19,
            'homeTeam_goal'=>1,
            'awayTeam_goal'=>1,
            'home_points'=>1,
            'away_points'=>1,
            'home_xG'=>1.37,
            'away_xG'=>1.07,
            'home_ballPossession'=>63,
            'away_ballPossession'=>37,
            'home_shots'=>14,
            'away_shots'=>16,
            'home_shotsOnTarget'=>5,
            'away_shotsOnTarget'=>3,
            'home_corners'=>10,
            'away_corners'=>4,
            'home_offsides'=>0,
            'away_offsides'=>2,
            'home_fouls'=>9,
            'away_fouls'=>14,
            'home_yellow'=>1,
            'away_yellow'=>4,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:24:13',
            'updated_at'=>'2024-01-24 17:24:13'
            ] );
                        
            Result::create( [
            'id'=>4,
            'fixture_id'=>4,
            'matchday'=>1,
            'home_team'=>5,
            'away_team'=>12,
            'homeTeam_goal'=>4,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>4.01,
            'away_xG'=>1.48,
            'home_ballPossession'=>71,
            'away_ballPossession'=>29,
            'home_shots'=>27,
            'away_shots'=>9,
            'home_shotsOnTarget'=>12,
            'away_shotsOnTarget'=>3,
            'home_corners'=>6,
            'away_corners'=>7,
            'home_offsides'=>2,
            'away_offsides'=>3,
            'home_fouls'=>11,
            'away_fouls'=>12,
            'home_yellow'=>2,
            'away_yellow'=>2,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:25:13',
            'updated_at'=>'2024-01-24 17:25:13'
            ] );
                        
            Result::create( [
            'id'=>5,
            'fixture_id'=>5,
            'matchday'=>1,
            'home_team'=>9,
            'away_team'=>10,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>1,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>2.73,
            'away_xG'=>1.5,
            'home_ballPossession'=>41,
            'away_ballPossession'=>59,
            'home_shots'=>19,
            'away_shots'=>9,
            'home_shotsOnTarget'=>9,
            'away_shotsOnTarget'=>2,
            'home_corners'=>10,
            'away_corners'=>4,
            'home_offsides'=>6,
            'away_offsides'=>3,
            'home_fouls'=>12,
            'away_fouls'=>6,
            'home_yellow'=>0,
            'away_yellow'=>2,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:26:15',
            'updated_at'=>'2024-01-24 17:26:15'
            ] );
                        
            Result::create( [
            'id'=>6,
            'fixture_id'=>6,
            'matchday'=>1,
            'home_team'=>17,
            'away_team'=>8,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>1,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>0.51,
            'away_xG'=>1.89,
            'home_ballPossession'=>32,
            'away_ballPossession'=>68,
            'home_shots'=>8,
            'away_shots'=>24,
            'home_shotsOnTarget'=>1,
            'away_shotsOnTarget'=>8,
            'home_corners'=>5,
            'away_corners'=>5,
            'home_offsides'=>2,
            'away_offsides'=>2,
            'home_fouls'=>18,
            'away_fouls'=>11,
            'home_yellow'=>3,
            'away_yellow'=>0,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:27:37',
            'updated_at'=>'2024-01-24 17:27:37'
            ] );
                        
            Result::create( [
            'id'=>7,
            'fixture_id'=>7,
            'matchday'=>1,
            'home_team'=>15,
            'away_team'=>2,
            'homeTeam_goal'=>5,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>3.41,
            'away_xG'=>1.77,
            'home_ballPossession'=>53,
            'away_ballPossession'=>47,
            'home_shots'=>17,
            'away_shots'=>16,
            'home_shotsOnTarget'=>13,
            'away_shotsOnTarget'=>6,
            'home_corners'=>6,
            'away_corners'=>5,
            'home_offsides'=>2,
            'away_offsides'=>0,
            'home_fouls'=>12,
            'away_fouls'=>17,
            'home_yellow'=>4,
            'away_yellow'=>4,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:28:28',
            'updated_at'=>'2024-01-24 17:28:28'
            ] );
                        
            Result::create( [
            'id'=>8,
            'fixture_id'=>8,
            'matchday'=>1,
            'home_team'=>4,
            'away_team'=>18,
            'homeTeam_goal'=>2,
            'awayTeam_goal'=>2,
            'home_points'=>1,
            'away_points'=>1,
            'home_xG'=>2.22,
            'away_xG'=>1.27,
            'home_ballPossession'=>30,
            'away_ballPossession'=>70,
            'home_shots'=>11,
            'away_shots'=>18,
            'home_shotsOnTarget'=>6,
            'away_shotsOnTarget'=>6,
            'home_corners'=>3,
            'away_corners'=>6,
            'home_offsides'=>1,
            'away_offsides'=>0,
            'home_fouls'=>12,
            'away_fouls'=>13,
            'home_yellow'=>1,
            'away_yellow'=>4,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:29:21',
            'updated_at'=>'2024-01-24 17:29:21'
            ] );
                        
            Result::create( [
            'id'=>9,
            'fixture_id'=>9,
            'matchday'=>1,
            'home_team'=>7,
            'away_team'=>11,
            'homeTeam_goal'=>1,
            'awayTeam_goal'=>1,
            'home_points'=>1,
            'away_points'=>1,
            'home_xG'=>1.35,
            'away_xG'=>1.28,
            'home_ballPossession'=>65,
            'away_ballPossession'=>35,
            'home_shots'=>10,
            'away_shots'=>13,
            'home_shotsOnTarget'=>4,
            'away_shotsOnTarget'=>1,
            'home_corners'=>4,
            'away_corners'=>4,
            'home_offsides'=>3,
            'away_offsides'=>5,
            'home_fouls'=>5,
            'away_fouls'=>13,
            'home_yellow'=>3,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:30:31',
            'updated_at'=>'2024-01-24 17:30:31'
            ] );
                        
            Result::create( [
            'id'=>10,
            'fixture_id'=>10,
            'matchday'=>1,
            'home_team'=>14,
            'away_team'=>20,
            'homeTeam_goal'=>1,
            'awayTeam_goal'=>0,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>2.21,
            'away_xG'=>2.35,
            'home_ballPossession'=>51,
            'away_ballPossession'=>49,
            'home_shots'=>15,
            'away_shots'=>23,
            'home_shotsOnTarget'=>3,
            'away_shotsOnTarget'=>6,
            'home_corners'=>8,
            'away_corners'=>7,
            'home_offsides'=>1,
            'away_offsides'=>3,
            'home_fouls'=>15,
            'away_fouls'=>10,
            'home_yellow'=>2,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:31:26',
            'updated_at'=>'2024-01-24 17:31:26'
            ] );
                        
            Result::create( [
            'id'=>11,
            'fixture_id'=>11,
            'matchday'=>2,
            'home_team'=>2,
            'away_team'=>9,
            'homeTeam_goal'=>4,
            'awayTeam_goal'=>0,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>3,
            'away_xG'=>0.63,
            'home_ballPossession'=>60,
            'away_ballPossession'=>40,
            'home_shots'=>13,
            'away_shots'=>9,
            'home_shotsOnTarget'=>7,
            'away_shotsOnTarget'=>2,
            'home_corners'=>7,
            'away_corners'=>6,
            'home_offsides'=>1,
            'away_offsides'=>1,
            'home_fouls'=>8,
            'away_fouls'=>12,
            'home_yellow'=>3,
            'away_yellow'=>4,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:32:34',
            'updated_at'=>'2024-01-24 17:32:34'
            ] );
                        
            Result::create( [
            'id'=>12,
            'fixture_id'=>12,
            'matchday'=>2,
            'home_team'=>8,
            'away_team'=>1,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>1,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>1.01,
            'away_xG'=>2.02,
            'home_ballPossession'=>47,
            'away_ballPossession'=>53,
            'home_shots'=>14,
            'away_shots'=>14,
            'home_shotsOnTarget'=>2,
            'away_shotsOnTarget'=>3,
            'home_corners'=>1,
            'away_corners'=>8,
            'home_offsides'=>0,
            'away_offsides'=>2,
            'home_fouls'=>14,
            'away_fouls'=>10,
            'home_yellow'=>2,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>1,
            'created_at'=>'2024-01-24 17:33:27',
            'updated_at'=>'2024-01-24 17:33:27'
            ] );
                        
            Result::create( [
            'id'=>13,
            'fixture_id'=>13,
            'matchday'=>2,
            'home_team'=>10,
            'away_team'=>4,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>3,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>0.46,
            'away_xG'=>3.93,
            'home_ballPossession'=>55,
            'away_ballPossession'=>45,
            'home_shots'=>10,
            'away_shots'=>17,
            'home_shotsOnTarget'=>2,
            'away_shotsOnTarget'=>8,
            'home_corners'=>5,
            'away_corners'=>5,
            'home_offsides'=>1,
            'away_offsides'=>4,
            'home_fouls'=>13,
            'away_fouls'=>12,
            'home_yellow'=>4,
            'away_yellow'=>2,
            'home_red'=>1,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:34:34',
            'updated_at'=>'2024-01-24 17:34:34'
            ] );
                        
            Result::create( [
            'id'=>14,
            'fixture_id'=>14,
            'matchday'=>2,
            'home_team'=>11,
            'away_team'=>3,
            'homeTeam_goal'=>3,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>3.08,
            'away_xG'=>1.29,
            'home_ballPossession'=>65,
            'away_ballPossession'=>35,
            'home_shots'=>26,
            'away_shots'=>13,
            'home_shotsOnTarget'=>10,
            'away_shotsOnTarget'=>5,
            'home_corners'=>10,
            'away_corners'=>2,
            'home_offsides'=>0,
            'away_offsides'=>3,
            'home_fouls'=>11,
            'away_fouls'=>13,
            'home_yellow'=>1,
            'away_yellow'=>3,
            'home_red'=>1,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:35:26',
            'updated_at'=>'2024-01-24 17:35:26'
            ] );
                        
            Result::create( [
            'id'=>15,
            'fixture_id'=>16,
            'matchday'=>2,
            'home_team'=>13,
            'away_team'=>15,
            'homeTeam_goal'=>1,
            'awayTeam_goal'=>0,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>NULL,
            'away_xG'=>NULL,
            'home_ballPossession'=>1,
            'away_ballPossession'=>0,
            'home_shots'=>14,
            'away_shots'=>7,
            'home_shotsOnTarget'=>4,
            'away_shotsOnTarget'=>1,
            'home_corners'=>3,
            'away_corners'=>0,
            'home_offsides'=>1,
            'away_offsides'=>4,
            'home_fouls'=>13,
            'away_fouls'=>11,
            'home_yellow'=>1,
            'away_yellow'=>5,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:36:30',
            'updated_at'=>'2024-01-24 17:36:30'
            ] );
                        
            Result::create( [
            'id'=>16,
            'fixture_id'=>17,
            'matchday'=>2,
            'home_team'=>16,
            'away_team'=>17,
            'homeTeam_goal'=>2,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>1.39,
            'away_xG'=>0.5,
            'home_ballPossession'=>50,
            'away_ballPossession'=>50,
            'home_shots'=>16,
            'away_shots'=>7,
            'home_shotsOnTarget'=>4,
            'away_shotsOnTarget'=>3,
            'home_corners'=>6,
            'away_corners'=>7,
            'home_offsides'=>3,
            'away_offsides'=>2,
            'home_fouls'=>5,
            'away_fouls'=>9,
            'home_yellow'=>2,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:37:28',
            'updated_at'=>'2024-01-24 17:37:28'
            ] );
                        
            Result::create( [
            'id'=>17,
            'fixture_id'=>18,
            'matchday'=>2,
            'home_team'=>18,
            'away_team'=>14,
            'homeTeam_goal'=>2,
            'awayTeam_goal'=>0,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>1.74,
            'away_xG'=>2.07,
            'home_ballPossession'=>56,
            'away_ballPossession'=>44,
            'home_shots'=>17,
            'away_shots'=>22,
            'home_shotsOnTarget'=>6,
            'away_shotsOnTarget'=>6,
            'home_corners'=>5,
            'away_corners'=>6,
            'home_offsides'=>1,
            'away_offsides'=>4,
            'home_fouls'=>9,
            'away_fouls'=>8,
            'home_yellow'=>1,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:38:21',
            'updated_at'=>'2024-01-24 17:38:21'
            ] );
                        
            Result::create( [
            'id'=>18,
            'fixture_id'=>19,
            'matchday'=>2,
            'home_team'=>19,
            'away_team'=>7,
            'homeTeam_goal'=>3,
            'awayTeam_goal'=>1,
            'home_points'=>3,
            'away_points'=>0,
            'home_xG'=>1.8,
            'away_xG'=>2.49,
            'home_ballPossession'=>24,
            'away_ballPossession'=>76,
            'home_shots'=>12,
            'away_shots'=>17,
            'home_shotsOnTarget'=>6,
            'away_shotsOnTarget'=>4,
            'home_corners'=>3,
            'away_corners'=>9,
            'home_offsides'=>3,
            'away_offsides'=>2,
            'home_fouls'=>12,
            'away_fouls'=>9,
            'home_yellow'=>4,
            'away_yellow'=>3,
            'home_red'=>1,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:39:25',
            'updated_at'=>'2024-01-24 17:39:25'
            ] );
                        
            Result::create( [
            'id'=>19,
            'fixture_id'=>20,
            'matchday'=>2,
            'home_team'=>20,
            'away_team'=>5,
            'homeTeam_goal'=>1,
            'awayTeam_goal'=>4,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>2.14,
            'away_xG'=>2.22,
            'home_ballPossession'=>46,
            'away_ballPossession'=>54,
            'home_shots'=>16,
            'away_shots'=>16,
            'home_shotsOnTarget'=>5,
            'away_shotsOnTarget'=>8,
            'home_corners'=>5,
            'away_corners'=>3,
            'home_offsides'=>4,
            'away_offsides'=>7,
            'home_fouls'=>14,
            'away_fouls'=>11,
            'home_yellow'=>5,
            'away_yellow'=>6,
            'home_red'=>1,
            'away_red'=>0,
            'created_at'=>'2024-01-24 17:40:21',
            'updated_at'=>'2024-01-24 17:40:21'
            ] );
                        
            Result::create( [
            'id'=>21,
            'fixture_id'=>21,
            'matchday'=>3,
            'home_team'=>1,
            'away_team'=>10,
            'homeTeam_goal'=>2,
            'awayTeam_goal'=>2,
            'home_points'=>1,
            'away_points'=>1,
            'home_xG'=>3.2,
            'away_xG'=>0.56,
            'home_ballPossession'=>71,
            'away_ballPossession'=>29,
            'home_shots'=>19,
            'away_shots'=>8,
            'home_shotsOnTarget'=>11,
            'away_shotsOnTarget'=>3,
            'home_corners'=>8,
            'away_corners'=>3,
            'home_offsides'=>4,
            'away_offsides'=>1,
            'home_fouls'=>6,
            'away_fouls'=>5,
            'home_yellow'=>0,
            'away_yellow'=>6,
            'home_red'=>0,
            'away_red'=>1,
            'created_at'=>'2024-01-24 20:31:14',
            'updated_at'=>'2024-01-24 20:31:14'
            ] );
                        
            Result::create( [
            'id'=>22,
            'fixture_id'=>22,
            'matchday'=>3,
            'home_team'=>3,
            'away_team'=>18,
            'homeTeam_goal'=>0,
            'awayTeam_goal'=>2,
            'home_points'=>0,
            'away_points'=>3,
            'home_xG'=>0.67,
            'away_xG'=>2.06,
            'home_ballPossession'=>43,
            'away_ballPossession'=>57,
            'home_shots'=>11,
            'away_shots'=>17,
            'home_shotsOnTarget'=>3,
            'away_shotsOnTarget'=>6,
            'home_corners'=>6,
            'away_corners'=>2,
            'home_offsides'=>3,
            'away_offsides'=>0,
            'home_fouls'=>18,
            'away_fouls'=>11,
            'home_yellow'=>1,
            'away_yellow'=>3,
            'home_red'=>0,
            'away_red'=>0,
            'created_at'=>'2024-01-24 20:48:59',
            'updated_at'=>'2024-01-24 20:48:59'
            ] );
    }
}
